general {
    gaps_in = 4
    gaps_out = 5
    border_size = 0
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 2
    rounding_power = 2
    active_opacity = 1
    inactive_opacity = 0.8

    shadow {
        enabled = true
        range = 12
        render_power = 4
        color = rgba(00000099)
    }

    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = snappy,0.3,1.2,0.4,1
    bezier = quick,0.15,0,0.1,1
    bezier = linear,0,0,1,1
    bezier = fastSmooth,0.4,0,0.2,1
    animation = global, 1, 6, fastSmooth
    animation = border, 1, 4.5, easeOutQuint
    animation = windows, 1, 3.6, fastSmooth
    animation = windowsIn, 1, 3.4, snappy, popin 88%
    animation = windowsOut, 1, 1.3, snappy, popin 85%
    animation = fadeIn, 1, 1.6, quick
    animation = fadeOut, 1, 1.3, quick
    animation = fade, 1, 2.6, quick
    animation = layers, 1, 3.3, fastSmooth
    animation = layersIn, 1, 3.6, snappy, fade
    animation = layersOut, 1, 1.3, snappy, fade
    animation = fadeLayersIn, 1, 1.6, quick
    animation = fadeLayersOut, 1, 1.3, quick
    animation = workspaces, 1, 1.6, snappy, fade
    animation = workspacesIn, 1, 1.1, snappy, fade
    animation = workspacesOut, 1, 1.6, snappy, fade
}

dwindle {
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}
