input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules =
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = 0.2
    accel_profile = adaptive
    natural_scroll = false

    touchpad {
        natural_scroll = false
        disable_while_typing = true
    }
}

gesture = 3, horizontal, workspace

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_invert = false
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
